[package]
name = "chatterbox"
version = "0.1.0"
authors = ["truefedex"]

[dependencies]
hound = "1.1.0"
rand = "0.3.0"
rustc-serialize = "0.3.19"
log = "0.3.6"
simplelog = "0.1.0"
getopts = "0.2.14"
libc = "0.2.10"
iron = "0.3.0"
staticfile = "0.2.0"
mount = "0.1.0"
